### ISSUE TITLE
Overflow Issue in Public Wall and Chat Screen 

### ISSUE THREAD

**Issue by HarshMakwana27** [nitin-787/uni-notes#129]
### Description

I have identified an overflow issue in app, specifically in the Public Wall and Chat Screen functionalities. The issue manifests itself as an overflow problem, where the content extends beyond the boundaries of the designated area.

**Steps to Reproduce:**

Launch the MyNotes app on a mobile device.
Navigate to the Public Wall section.
Observe that the content overflows beyond the bottom and right edges of the screen.
Repeat the same process for the Chat Screen.
Notice the overflow issue in the chat messages, making it challenging to read complete conversations.

**Expected Behavior:**
The content in both the Public Wall and Chat Screen should be properly contained within the designated areas, without any overflow beyond the edges of the screen. Users should be able to view all the content without any content being hidden or cut off.

**Device Information:**

Device: Realme GT neo2
OS: Android

Screenshots and additional information can be provided to further illustrate the issue. Let's work together to address this overflow problem and improve the user experience of app.

### Screenshots

<img src="https://github.com/nitin-787/uni-notes/assets/133812075/612c1d7a-d414-4dbc-8f3e-1875a8a46b25" height="600">
<img src="https://github.com/nitin-787/uni-notes/assets/133812075/655aa8e2-9562-408d-ad15-a39bf0c39d02" height="600">

**Comment by nitin-787** [comment]
will start this app's development again

**Comment by nitin-787** [comment]
you can refer this file, if you wanna work on it: https://github.com/nitin-787/uni-notes/blob/main/lib/config/size_config.dart
